# more info:
# https://config.travis-ci.com/
dist: bionic

language: go

go:
  - 1.14.x

git:
  depth: 1

jobs:
  include:
    - stage: static check
      install:
        # install golangci lint
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.27.0
      script:
        # run golangci lint checks
        - ./bin/golangci-lint run
    - stage: test
      script: go test -v ./cmd
    - # test
      services:
        - docker
        - redis
        - postgresql
      install:
        # setup kafka
        - ./travis/setup-kafka.sh
        # wait for kafka start
        - ./travis/await-kafka.sh
        # setup aerospike
        - ./travis/setup-aerospike.sh
        # wait for aerospike start
        - ./travis/await-aerospike.sh
        # setup postgreSQL
        - ./travis/setup-postgres.sh
      script: go test -v ./internal

notifications:
  email: false
