# more info:
# https://config.travis-ci.com/
dist: bionic

language: go

go:
  - 1.14.x

git:
  depth: 1

jobs:
  include:
    - stage: test
      script: go test -v ./cmd
    - # test
      services:
        - docker
      before_install:
        - ./travis/setup-kafka.sh
        - ./travis/await-kafka.sh
      install:
        # setup aerospike
        - ./travis/aerospike-setup.sh
        # start aerospike
        - sudo systemctl start aerospike
      script: go test -v ./internal
    - stage: simple
      script: ./simulate-sleep.sh

notifications:
  email: false
