# more info:
# https://config.travis-ci.com/
dist: bionic

language: go

go:
  - 1.14.x

git:
  depth: 1

jobs:
  include:
    - stage: test
      script: go test -v ./cmd
    - # test
      script: go test -v ./internal
    - stage: simple
      script: ./simulate-sleep.sh

notifications:
  email: false
