# more info:
# https://config.travis-ci.com/
dist: bionic

language: go

go:
  - 1.14.x

git:
  depth: 1

jobs:
  include:
    - stage: test
      script: go test -v ./cmd
    - # test
      install:
        # download
        - wget -O aerospike.tgz 'https://www.aerospike.com/download/server/latest/artifact/ubuntu18'
        # untar
        - tar xvzf aerospike.tgz # will extract: aerospike-server-community-5.0.0.4-ubuntu18.04
        # install
        - cd $(ls | grep "aerospike-server-community")
        - sudo ./asinstall
        # start aerospike
        - sudo systemctl start aerospike
        # go back to source
        - cd ..
      script: go test -v ./internal
    - stage: simple
      script: ./simulate-sleep.sh

notifications:
  email: false
