// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package internal

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson215cb26eDecodeGithubComTesteradjustSimpleCobraAppInternal(in *jlexer.Lexer, out *EzJsonPerson) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "age":
			out.Age = int(in.Int())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson215cb26eEncodeGithubComTesteradjustSimpleCobraAppInternal(out *jwriter.Writer, in EzJsonPerson) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"age\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Age))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EzJsonPerson) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson215cb26eEncodeGithubComTesteradjustSimpleCobraAppInternal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EzJsonPerson) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson215cb26eEncodeGithubComTesteradjustSimpleCobraAppInternal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EzJsonPerson) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson215cb26eDecodeGithubComTesteradjustSimpleCobraAppInternal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EzJsonPerson) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson215cb26eDecodeGithubComTesteradjustSimpleCobraAppInternal(l, v)
}
